site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

pages:
- Home: 'index.md'
- Building the firmware: 'build.md'
- Flashing the firmware: 'flash.md'
- FAQ: 'faq.md'
- Support: 'support.md'
- Modules:
    - 'node': 'modules/node.md'