site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_css:
- css/extra.css
extra_javascript:
- js/extra.js

site_favicon: img/favicon.png

pages:
- Overview: 'index.md'
- English:
    - Home: 'en/index.md'
    - Building the firmware: 'en/build.md'
    - Flashing the firmware: 'en/flash.md'
    - FAQ: 'en/faq.md'
    - Support: 'en/support.md'
    - Modules:
        - 'adc': 'en/modules/adc.md'
        - 'node': 'en/modules/node.md'
        - 'file': 'en/modules/file.md'
        - 'rtcmem': 'en/modules/rtcmem.md'
        - 'rtctime': 'en/modules/rtctime.md'
        - 'rtcfifo': 'en/modules/rtcfifo.md'
        - 'sntp': 'en/modules/sntp.md'
- Deutsch:
    - Home: 'de/index.md'
