site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

pages:
- Overview: 'index.md'
- English:
    - Home: 'EN/index.md'
    - Building the firmware: 'EN/build.md'
    - Flashing the firmware: 'EN/flash.md'
    - FAQ: 'EN/faq.md'
    - Support: 'EN/support.md'
    - Modules:
        - 'node': 'EN/modules/node.md'
- Deutsch:
    - Home: 'DE/index.md'