site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird du to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_css:
- css/extra.css
extra_javascript:
- js/extra.js

site_favicon: img/favicon.png

pages:
- Overview: 'index.md'
- English:
    - Home: 'EN/index.md'
    - Building the firmware: 'EN/build.md'
    - Flashing the firmware: 'EN/flash.md'
    - FAQ: 'EN/faq.md'
    - Support: 'EN/support.md'
    - Modules:
        - 'node': 'EN/modules/node.md'
- Deutsch:
    - Home: 'DE/index.md'